# Generated by Django 3.1.7 on 2021-04-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='category',
            field=models.CharField(default='Action', max_length=200),
        ),
    ]
