# Generated by Django 3.1.7 on 2021-04-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapi', '0003_auto_20210420_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/None/Noimg.jpg', upload_to='images/'),
        ),
    ]
